services:
  - type: web
    runtime: docker
    name: login-orcest-ai
    plan: starter
    repo: https://github.com/orcest-ai/login
    branch: main
    rootDir: /
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1
    domains:
      - login.orcest.ai
    healthCheckPath: /health
    envVars:
      - key: SSO_SECRET_KEY
        sync: false
      - key: SSO_ADMIN_EMAIL
        sync: false
      - key: SSO_ADMIN_PASSWORD
        sync: false
